# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
# url: http://username.github.io/
# baseurl: /sustain4-theme
title: Chris Turner
author: Chris Turner
description: Personal blog and resume
avatar: profile.png
email: yourname@email.com
github: jekyller/sustain # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]

sass:
    sass_dir: _sass

# Defining plugins here is necessary because certain hosts (e.g. Github Pages, Netlify) do not build sites using Bundler.
plugins:
  - jekyll-paginate
  - jekyll-menus
