# top level stuff you probably don't need to touch
highlighter: pygments
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://www.peterskaronis.com
baseurl: "https://www.peterskaronis.com/"
title: Peter Skaronis
author: Peter Skaronis
description: Personal blog and resume
avatar: profile.png
email: pskaronis@protonmail.com
github: techimpossible.github.com # username
twitter: Peter_Skaronis
linkedin: peterskaronis
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: peterskaronis
google_analytics: UA-45619220-1


# needed for travis-ci build
exclude: [vendor]

gems:
  - jekyll-sitemap
  - jekyll-paginate
