# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://Galapagos.github.io/
baseurl: /sustain/
title: Dan Esrey
author: Dan Esrey
description: Personal blog and resume
avatar: profile.png
email: dan.esrey@icloud.com
github: biomadeira/sustain # username
twitter: danesrey
linkedin: danesrey
stackoverflow:   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
// disqus: username
google_analytics: 


# needed for travis-ci build
exclude: [vendor]
