# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: pretty 
paginate: 5
gems: [jekyll-paginate]
safe: true


# edit here to achieve your personal greatness
url: http://egd.io/
baseurl: /
title: egd.io
author: Ethan Gregory Dodge
description: Privacy, tech, and opinions
avatar: avatar.jpg
email: ethan@egd.io
github: egd-io # username
twitter: egd_io
linkedin: ethandodge
#stackoverflow: username   #e.g: users/2735833/proton1h1
rss: atom.xml
#Comment out if you don't want disqus 
disqus: egd_io 
#google_analytics: UA-67800268-2 


# needed for travis-ci build
exclude: [vendor]
