# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /sustain/
title: Joseph Godwin Kimani
author: Joseph Godwin Kimani
description: Personal blog and Resume
avatar: profile.png
email: josephgodwinke@gmail.com
github: gochojr # username
twitter: josephgodwinke
linkedin: godwingocho
stackoverflow: users/5194112/joseph-godwinke   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: josephgodwinke
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
