# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://alancarlosilva.github.io/
baseurl: ""
title: Alan Silva - C4D
author: Alan Silva
description: Engenharia de Dados - [Dicas, códigos e muito conteúdo]
avatar: foto.png
email: alancards@gmail.com
github: alancarlosilva # username
#twitter: alancards
linkedin: alancarlossilva
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
